### ISSUE TITLE
    self.params.update(self.configs.__dict__['__flags']) KeyError: '__flags'

### ISSUE THREAD

**Issue by HLBTyhs** [Yunbo426/MIM#1]
self.params.update(self.configs.__dict__['__flags'])
KeyError: '__flags'

**Comment by ZJianjin** [comment]
I can‘t reproduce this bug. The code is based on TensorFlow1.4.1. Maybe the version of TF will cause this problem?

**Comment by HLBTyhs** [comment]
> I can‘t reproduce this bug. The code is based on TensorFlow1.4.1. Maybe the version of TF will cause this problem?

Thank you for your reminder.

**Comment by HLBTyhs** [comment]
> I can‘t reproduce this bug. The code is based on TensorFlow1.4.1. Maybe the version of TF will cause this problem?

Thank you for your reminder.

**Comment by HLBTyhs** [comment]
> I can‘t reproduce this bug. The code is based on TensorFlow1.4.1. Maybe the version of TF will cause this problem?

Thank you very much. I have solved the problem.

**Comment by ABadCandy** [comment]
@HLBTyhs Hi, I also encountered this problem, how can you solve it? My Tensorflow version is 2.0， should I change to 1.4.1?

**Comment by HansBambel** [comment]
> > I can‘t reproduce this bug. The code is based on TensorFlow1.4.1. Maybe the version of TF will cause this problem?
> 
> Thank you very much. I have solved the problem.

How did you solve the problem? I am facing the same issue and I can't install tensorflow 1.4.1 any more.

**Comment by HansBambel** [comment]
Never mind. I managed to make it work by substituting `tf.app` with `tf.compat.v1` and then in the `model_factory` the params were created like this: 
```
self.params = dict()
for k in self.configs:
    self.params[k] = self.configs[k].value
```
